### ISSUE TITLE
Magical Crops compat broken due to herbs being removed

### ISSUE THREAD

**Issue by monax3** [powercrystals/MineFactoryReloaded#100]
2013-05-08 05:48:12 [WARNING] [ForgeModLoader] Something went wrong in MFR Compat: Magical Crops. Probably Emy's fault.
2013-05-08 05:48:12 [INFO] [STDERR] java.lang.NoSuchFieldException: SeedHerbGuam
2013-05-08 05:48:12 [INFO] [STDERR]     at java.lang.Class.getField(Unknown Source)
2013-05-08 05:48:12 [INFO] [STDERR]     at powercrystals.minefactoryreloaded.modhelpers.magicalcrops.MagicalCrops.load(MagicalCrops.java:51)

Magical Crops 1.5.1.2.0.7:
- Removed: Herbs, Herb crops, herb mixtures, potions, pestle and mortar.

**Comment by Emys** [comment]
On it.

**Comment by monax3** [comment]
This sounds like a Magical Crops bug but after the fix I get this with MFR build 706 and Magical Crops 2.0.8a:

2013-05-10 20:23:07 [WARNING] [ForgeModLoader] Something went wrong in MFR Compat: Magical Crops. Probably Emy's fault.
2013-05-10 20:23:07 [INFO] [STDERR] java.lang.NoSuchMethodException: magicCrop.mCropObsidian.fertilize(net.minecraft.world.World, int, int, int)
