### ISSUE TITLE
Don't register null!

### ISSUE THREAD

**Issue by fogger** [powercrystals/MineFactoryReloaded#124]
This error has existed for a long time, but I can't find any other issue referring to it.  
surely I can't be the only one?

```
java.lang.RuntimeException: Don't register null!
  at net.minecraft.client.renderer.texture.TextureMap.func_94245_a(TextureMap.java:229)
  at net.minecraft.block.Block.func_94332_a(Block.java:1386)
  at net.minecraft.client.renderer.texture.TextureMap.func_94247_b(TextureMap.java:68)
  at net.minecraft.client.renderer.RenderEngine.func_94152_c(RenderEngine.java:520)
  at net.minecraft.client.renderer.RenderEngine.func_78352_b(RenderEngine.java:432)
  at cpw.mods.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:247)
  at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:479)
  at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
  at net.minecraft.client.Minecraft.run(Minecraft.java:733)
  at java.lang.Thread.run(Unknown Source)
```

**Reproducable with:**
- Fresh 1.5.2 instance
- **jar:** Forge 7.8.0.710
- **core:** PowerCrystalsCore 1.1.6-108
- **mods:** MineFactoryReloaded 2.6.0B1-818

**Comment by powercrystals** [comment]
This was a surprising pain to track down. Thanks for telling me it was one of my mods, though; I was assuming it was something else.
