### ISSUE TITLE
Class Cast Exception Crash.

### ISSUE THREAD

**Issue by Yoshi667** [powercrystals/MineFactoryReloaded#133]
Hey PC I set up a Cactus farm with water being used as a conveyor (Cactus grows, hits block, breaks, drops in water, flows with water). The problem I am having is that I set up two Item Collectors at the end of the water with a chest in between.

The first Cactus that broke off followed the water and as soon as it hit the item collector it crashed with ticking entity item Cactus.

Crash report:

Description: Ticking entity

java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.minecraftforge.common.ForgeDirection;
    at powercrystals.minefactoryreloaded.core.MFRUtil.directionsWithoutConveyors(MFRUtil.java:84)
    at powercrystals.minefactoryreloaded.tile.machine.TileEntityCollector.addToChests(TileEntityCollector.java:20)
    at powercrystals.minefactoryreloaded.block.BlockFactoryMachine.func_71869_a(BlockFactoryMachine.java:148)
    at net.minecraft.entity.Entity.func_70017_D(Entity.java:1023)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:967)
    at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:115)
    at net.minecraft.world.World.func_72866_a(World.java:2337)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:717)
    at net.minecraft.world.World.func_72870_g(World.java:2299)
    at net.minecraft.world.World.func_72939_s(World.java:2145)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:127)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

I'm looking into the hierarchy now to see if I can fix it but it might be faster for you.

**Comment by powercrystals** [comment]
What version are you on? This should have been fixed.

**Comment by Emys** [comment]
Should have been fixed here, specifically https://github.com/powercrystals/MineFactoryReloaded/commit/cf4be54630168388eade184e6da93ba7e38736a5

**Comment by Yoshi667** [comment]
Yeah was running a version from a week ago. Just re-forked to the latest and everything is working as intended.
