### ISSUE TITLE
Grinder SMP Crash (using build 887) java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#144]
We removed thaumcraft off the server recently.  My primary guess is that the grinder is trying to destroy an entity that now no longer exists faster than the server has a chance to remove the entity for no longer being valid.  I could be wrong but I have no real way to identify the exact problem right now.

java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:17)
        at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:31)
        at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.activateMachine(TileEntityGrinder.java:137)
        at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:133)
        at net.minecraft.world.World.func_72939_s(World.java:2272)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:787)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:898)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:794)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:678)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

http://pastebin.com/JbT36gqg

**Comment by jalapeno777** [comment]
Alright, after nuking the machines in the area I tracked the problem to the grinder trying to destroy a Mistwolf from Twilight Forest.  Not sure what the interaction problem is but there you go.  A non-fatal error in these kinds of situations if possible would be a good failsafe against any other mod mob interaction problems.
