### ISSUE TITLE
Build 1050: Atum compatibilty broken (non-fatal)

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#252]
The latest version is Atum 0.3.5B.  This error occurs during mod loadup.

2013-07-03 16:32:46 [INFO] Last updated for Atum 0.3.5A, current release as of May 20 2013
2013-07-03 16:32:46 [SEVERE] java.lang.NoSuchFieldException: itemFlaxSeeds
2013-07-03 16:32:46 [SEVERE]    at java.lang.Class.getField(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at powercrystals.minefactoryreloaded.modhelpers.atum.Atum.load(Atum.java:48)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-07-03 16:32:46 [SEVERE]    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:93)
2013-07-03 16:32:46 [SEVERE]    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:355)
2013-07-03 16:32:46 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:168)
2013-07-03 16:32:46 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574)
2013-07-03 16:32:46 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by Emys** [comment]
Looks like the latest is actually 0.4.3B

I'll update it anyway

https://github.com/powercrystals/MineFactoryReloaded/commit/088a412ae8df7805e861003f3b8e19d5d80bf5f1
