### ISSUE TITLE
Renaming a safarinet "fills" it and crashes the game upon attempting release

### ISSUE THREAD

**Issue by skyboy** [powercrystals/MineFactoryReloaded#257]
```

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.nbt.NBTTagList.func_74743_b(NBTTagList.java:106)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.spawnCreature(ItemSafariNet.java:254)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.releaseEntity(ItemSafariNet.java:209)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.func_77648_a(ItemSafariNet.java:180)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:149)
    at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:425)
    at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:553)
    at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
    at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:134)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
    at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:675)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:127)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**Comment by Emys** [comment]
fixed https://github.com/powercrystals/MineFactoryReloaded/commit/b187ad8e626e6947007fb2d5ab947fee1aaec483
