### ISSUE TITLE
1050 - Non-fatal java.lang.IllegalArgumentException: java.lang.ClassCastException

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#265]
This is running on smp so I'm not precisely sure the issue.  If you need me to work out a duplicating method please let me know.

11:35:25 AM CONSOLE: [SEVERE] java.lang.IllegalArgumentException: java.lang.ClassCastException@17f5d123
11:35:25 AM CONSOLE: [SEVERE] at sun.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
11:35:25 AM CONSOLE: [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
11:35:25 AM CONSOLE: [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
11:35:25 AM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.modhelpers.FertilizableCropReflection.fertilize(FertilizableCropReflection.java:41)
11:35:25 AM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.tile.machine.TileEntityFertilizer.activateMachine(TileEntityFertilizer.java:89)
11:35:25 AM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:180)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.world.World.func_72939_s(World.java:2351)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:786)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:820)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:716)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
11:35:25 AM CONSOLE: [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by jalapeno777** [comment]
At first glance this might be occurring from trying to fertilize a tree...specifically a spruce sapling.
