### ISSUE TITLE
[Crash] java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by iarspider** [powercrystals/MineFactoryReloaded#281]
Crashed for no obvious reason:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/13/13 10:53 AM
Description: Ticking tile entity

java.lang.UnsupportedOperationException
    at java.util.AbstractList.remove(AbstractList.java:161)
    at java.util.AbstractList$Itr.remove(AbstractList.java:374)
    at java.util.AbstractList.removeRange(AbstractList.java:571)
    at java.util.AbstractList.clear(AbstractList.java:234)
    at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.doDrop(TileEntityFactoryPowered.java:228)
    at powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester.activateMachine(TileEntityHarvester.java:152)
    at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:180)
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.util.AbstractList.remove(AbstractList.java:161)
    at java.util.AbstractList$Itr.remove(AbstractList.java:374)
    at java.util.AbstractList.removeRange(AbstractList.java:571)
    at java.util.AbstractList.clear(AbstractList.java:234)
    at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.doDrop(TileEntityFactoryPowered.java:228)
    at powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester.activateMachine(TileEntityHarvester.java:152)
    at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:180)

-- Tile entity being ticked --
Details:
    Name: factoryHarvester // powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester
    Block type: ID #3120 (tile.mfr.machine.0 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (86,74,188), Chunk: (at 6,4,12 in 5,11; contains blocks 80,0,176 to 95,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #3120 (tile.mfr.machine.0 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)

-- Affected level --
Details:
    Level name: Newer World
    All players: 1 total; [EntityPlayerMP['iarspider'/2803442, l='Newer World', x=112.33, y=78.00, z=201.11]]
    Chunk stats: ServerChunkCache: 469 Drop: 0
    Level seed: 1180396240585296996
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (105,64,209), Chunk: (at 9,4,1 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 18242222 game time, 18955030 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 28132 (now: false), thunder time: 3357 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Linux (amd64) version 3.2.0-49-generic
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 969504616 bytes (924 MB) / 2863333376 bytes (2730 MB) up to 2863333376 bytes (2730 MB)
    JVM Flags: 4 total; -Xms3G -Xmx3G -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
    AABB Pool Size: 3928 (219968 bytes; 0 MB) allocated, 3545 (198520 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v7.51 FML v5.2.21.727 Minecraft Forge 7.8.0.727 122 mods loaded, 122 mods active
    mcp{7.44} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.21.727} [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.0.727} [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chemcraft|Core{1.4.0} [Chemcraft Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.5} [CoFH Framework] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.7} [CodeChicken Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.28} [Not Enough Items] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8B1} [PowerCrystals Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocks{55.0.7} [Immibis's Microblocks] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v2.07(1.5.2)} [bspkrsCore] (bspkrsCorev2.07.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chemcraft|Network{1.0.0} [Chemcraft Network] (Chemcraft_Core_1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.5} [CoFHCore] (CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.5} [CoFHWorld] (CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denLib{3.0.14} [denLib] (denLib-1.5.2-3.0.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CreeperCollateral{2.0.1} [CreeperCollateral] (CreeperCollateral-1.5.2-2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocksInstallCheck{55.0.7} [Immibis's Microblocks (Checks for incorrect installation, ignore this)] (immibis-microblocks-55.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArsMagica{5.52.013} [Ars Magica] (ArsMagica_5.52.013.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.3.3} [BiblioCraft] (BiblioCraft[v1.3.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.1.1} [Natura] (Natura_2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{0.5.5} [Biomes O' Plenty] (Biomes-O-Plenty-0.5.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsBoP{0.1} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.0].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.5.1R2.7.0B8} [MFR Compat: Forestry (2)] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.4.6.0} [Thermal Expansion] (ThermalExpansion-2.4.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.116.350-lf} [IndustrialCraft 2] (industrialcraft-2_1.116.350-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.2.8.1} [Forestry for Minecraft] (forestry-A-2.2.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsForestry{0.1} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.0].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.2.12} [ChickenChunks] (ChickenChunks 1.3.2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.53} [ComputerCraft] (ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.53} [ComputerCraft Turtles] (ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{2.2.1} [DrZhark's CustomSpawner] (CustomMobSpawner 2.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Dynmap{1.9-92} [Dynmap] (Dynmap-HEAD-forge-7.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.15.1} [Enchanting Plus] (EnchantingPlus-1.15.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.2.12} [EnderStorage] (EnderStorage 1.4.2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{3.7.1} [BuildCraft] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{3.7.1} [BC Builders] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{3.7.1} [BC Energy] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{3.7.1} [BC Factory] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{3.7.1} [BC Transport] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.5.1R2.7.0B8} [MineFactory Reloaded] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{3.7.1} [BC Silicon] (buildcraft-A-3.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv11.c} [Applied Energistics] (appeng-rv11-c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{1.2.2c} [ExtraCells] (ExtraCells-universal-1.2.2c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{0.7.37} [Factorization] (Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{0.7.37} [Factorization Miscellaneous Nonsense] (Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.dimensionalSlice{0.7.37} [Factorization Dimensional Slices] (Factorization-0.7.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FlatBedrock{1.5.1R1.1.1} [FlatBedrock] (FlatBedrock-1.1.1-33.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NBTEdit{1.5.2.0} [In-game NBTEdit] (Forge_NBTEditv1.5.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{1.0.1} [iChunUtil] (iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviGun{1.5.1} [GraviGun] (GravityGun1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Hats{1.3.2} [Hats] (Hats1.3.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HatStand{1.2.1} [HatStand] (HatStand1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl{1.5.1c} [Nuclear Control] (IC2NuclearControl-1.5.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    INpureTools{1.0.18} [INpureTools] (INpureTools-1.5.2-1.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    INpureTools_CCTurtle{1.0.4} [INpureTools_CCTurtle] (INpureTools_CCTurtle-1.5.2-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.54b} [Inventory Tweaks] (InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PortalGun{1.5.2} [PortalGun] (PortalGun1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{7.3.0.0} [Railcraft] (Railcraft_1.5.2-7.3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts{2.0.0.a122} [Steve's Carts] (StevesCarts2.0.0.a122.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{3.0.5f} [Thaumcraft] (Thaumcraft3.0.5f.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.5.00} [Mystcraft] (mystcraft-uni-1.5.2-0.10.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.2} [The Twilight Forest] (twilightforest-1.18.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    KBITC3EssenceAddon{2.3.2} [ThaumCraft3 Essence Addons] (KBI TC3 Essentia Everything Addon for 1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.5.1_1.3.6.7} [Tinkers' Construct] (TConstruct_1.3.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    KBItinkersmelt{1.2.1} [KBI Tinker's Construct Smeltery Addon] (KBI Tinkers Construct Recovery Addon 1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (MFR-ForestryTrees-1.5.2-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore{1.7.0b} [Binnie Core] (binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTrees{1.7.0b} [Extra Trees] (binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (MFR-ForestryTrees-1.5.2-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mmmPowersuits{0.7.0-534} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.7.0-534.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowersuitAddons{0.2.3-157} [Andrew2448's Modular Powersuits Addon] (MPSA-0.2.3-157_MPS-531+.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.5.1R2.7.0B8} [MFR Compat: Applied Energistics] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.5.1R2.7.0B8} [MFR Compat: Atum] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.5.1R2.7.0B8} [MFR Compat: BackTools] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.5.1R2.7.0B8} [MFR Compat: Chococraft] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.7.0B8} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.5.1R2.7.0B8} [MFR Compat: Forestry] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.5.1R2.7.0B8} [MFR Compat: IC2] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.7.0B8} [MFR Compat: Magical Crops] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.5.1R2.7.0B8} [MFR Compat: Mystcraft] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.5.1R2.7.0B8} [MFR Compat: Pam's Mods] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.5.1R2.7.0B8} [MFR Compat: Railcraft] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.5.1R2.7.0B8} [MFR Compat: RP2] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.7.0B8} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatThaumcraft{1.5.1R2.7.0B8} [MFR Compat: Thaumcraft] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.5.1R2.7.0B8} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.5.1R2.7.0B8} [MFR Compat: TwilightForest] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.5.1R2.7.0B8} [MFR Compat: Vanilla] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.5.1R2.7.0B8} [MFR Compat: XyCraft] (MineFactoryReloaded-2.7.0B8-1077.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ModularForceFieldSystem{2.3.0.1.15} [Modular ForceField System V2] (ModularForcefieldSystem-2.3.0.1.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.0.9.3} [NEI Plugins] (NEIPlugins-1.0.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR] (Natura_2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.5.1R2.1.5} [Nether Ores] (NetherOres-2.1.5-76.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PluginsforForestry{3.0.17} [PluginsforForestry] (PluginsforForestry-1.5.2-3.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters{1.5.1R2.3.1} [Power Converters] (PowerConverters-2.3.1-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JAKJ_RedstoneInMotion{1.1.1.0} [Redstone In Motion] (RedstoneInMotion_1.1.1.0_mc1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Refined BioFuel{1.2.0} [Refined BioFuel] (Refined Biofuel 1.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    xreliquary{1.5.2} [Xeno's Reliquary] (Reliquary1.0.6d.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    secretroomsmod{4.6.0} [SecretRoomsMod] (SecretRoomsMod-universal-4.6.0.283.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards{1.0.16} [Soul Shards] (SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR] (TConstruct_1.3.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{1.0.7} [Thaumic Tinkerer] (Thaumic Tinkerer [1.0.7].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.12.13} [Backpack] (backpack-1.12.13-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees{1.7.0b} [Extra Bees] (binnie-mods-1.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChargePads{2.7.0} [Charge Pads] (chargepads-1.5.2-universal-2.7.0.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactSolars{4.2.0.52} [Compact Solar Arrays] (compactsolars-universal-1.5.2-4.2.0.52.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EE3{pre1h (build 16)} [Equivalent Exchange 3] (ee3-universal-pre1h-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{0.2.4c} [Extra Utilities] (extrautils - 0.2.4c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{55.1.6} [Immibis Core] (immibis-core-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.2.8.446} [Iron Chest] (ironchest-universal-1.5.2-5.2.8.446.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MagicBees{2.0.2} [Magic Bees] (magicbees-2.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MiscPeripherals{3.3} [MiscPeripherals] (miscperipherals-3.3f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite{1.9.3} [Gravitation Suite] (mod_zGraviSuite_1_9_3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.8.1.r27} [NEI Addons] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|AE{1.8.1.r27} [NEI Addons: Applied Energistics] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.8.1.r27} [NEI Addons: Crafting Tables] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.8.1.r27} [NEI Addons: Extra Bees] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.8.1.r27} [NEI Addons: Forestry] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.8.1.r27} [NEI Addons: Misc Peripherals] (neiaddons-1.5.2-1.8.1.r27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidiPlates{1.5.0} [Obsidian Pressure Plates] (obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedLogic{55.4.1} [RedLogic] (redlogic-55.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chemcraft|MoreBackpacks{2.1.4} [More Backpacks] (More_Backpacks_2.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OmniTools{3.1.6.0} [OmniTools] (OmniTools-3.1.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 855 (47880 bytes; 0 MB) allocated, 855 (47880 bytes; 0 MB) used
    Player Count: 1 / 20; [EntityPlayerMP['iarspider'/2803442, l='Newer World', x=112.33, y=78.00, z=201.11]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by iarspider** [comment]
This harvester was used to collect from OreBerry bushes (from Natura/TConstruct). The container (EnderChest from EnderStorage mod) got full, that was probably the reason for this crash.

**Comment by iarspider** [comment]
I'm currently 99% sure that the crash was caused by Harvester not being able to put anything into output chest.

**Comment by skyboy** [comment]
This was fixed in build 1079. (commit 16e1e5efa905548ff7ed5a3ba7781036d5552e74)
