### ISSUE TITLE
Non-fatal error (SMP): java.lang.IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#290]
This occurs for some players using fertilizers, unfortunately being an SMP server I can't determine exactly the source of the issue (ie bad items in fertilizers, trying to fertilize something it should be able to but can't, etc) since there's no indication of where the offending block is indicated.  It happens pretty consistently though.

1:37:17 PM CONSOLE: [SEVERE] java.lang.IllegalArgumentException: object is not an instance of declaring class
1:37:17 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1:37:17 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
1:37:17 PM CONSOLE: [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
1:37:17 PM CONSOLE: [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
1:37:17 PM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.modhelpers.FertilizableCropReflection.fertilize(FertilizableCropReflection.java:41)
1:37:17 PM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.tile.machine.TileEntityFertilizer.activateMachine(TileEntityFertilizer.java:96)
1:37:17 PM CONSOLE: [SEVERE] at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:180)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.world.World.func_72939_s(World.java:2351)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:786)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:820)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:716)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
1:37:17 PM CONSOLE: [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by jalapeno777** [comment]
Actually worked out this is caused by using Industrial fertilizer with a fertilizer machine that has a range upgrade.

Without the range upgrade the error doesn't show up and the machine works as intended.  WITH the upgrade however the machine doesn't work at all and the console is spammed the above error

**Comment by jalapeno777** [comment]
scratch that....after further testing the issue is the range of the fertilizer was running into a cobblestone wall and the error occurs when the fertilizer was trying to "grow" the wall
