### ISSUE TITLE
Misuse of random causes crash due to n < 1 in TileEntityAutoDisenchanter.java:115

### ISSUE THREAD

**Issue by sibomots** [powercrystals/MineFactoryReloaded#348]
In this code:

 TileEntityAutoDisenchanter.java:115

```
                                    int enchIndex = worldObj.rand.nextInt(((NBTTagList)_inventory[2].getTagCompound().getTag("ench")).tagCount());
                                    enchTag = (NBTTagCompound)((NBTTagList)_inventory[2].getTagCompound().getTag("ench")).tagAt(enchIndex);
```

This error is caused.

java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Random.java:300)
        at powercrystals.minefactoryreloaded.tile.machine.TileEntityAutoDisenchanter.activateMachine(TileEntityAutoDisenchanter.java:115)
        at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_70316_g(TileEntityFactoryPowered.java:133)

PLEASE -- if you're going to call rand.nextInt, test the argument before hand.  It's safer and smarter to do so.

I don't know fully what the intent of this is (I haven't studied your source long enough to know), but something along these lines would be highly preferred:

[ in fact, I am very dubious about the dereference into the inventory array... what if there are not 3 elements?   then xxx_inventory[2] would also fault..)

// snip --

// So I'm going to give you the more pedantic way to do this safer, 
// you can come up with your own elegant way.  First check the 
// size of an array you're dereferencing..

// you should do even more checking,.  What if there is no "ench" tag on an object,
// then the result is null and you're calling getCount on a null object, etc..
//  Be safer throughout your code.  Cascaded member function 
// operators "." is just asking for trouble.

int x = 0;

if (NBTTagList_inventory.size() > 2)  {
  x = ((NBTTagList)_inventory[2].getTagCompound().getTag("ench")).tagCount();
}

int enchIndex = 0;

// Then check that the argument we intend to pass to rand.nextInt is large enough

if (x >= 1) {
    enchIndex = worldObj.rand.nextInt(x);
}

// This way enchIndex is 0 if the argument for rand.nextInt is less than 1.

// I'm not sure yet if that's kosher for the algorithm, you would know.
//  But the point is:  please do not just pass any kind of argument
// into rand.nextInt without checking the value.  
// We know from the API of Java that rand.nextInt will throw an
// exception if the argument is 0, so this is tantamount to using
// a pointer without checking if it's null.

Hope this helps, let me know if you need any help.

By the way, thanks for the mod.  Nice work!

**Comment by skyboy** [comment]
I'm maintaining the mod presently (1.6 onwards); (over here: https://github.com/skyboy/MineFactoryReloaded)

This issue was resolved recently, and nothing in the pedantic (your words) code you provided is correct, nor appreciated.

**Comment by sibomots** [comment]
I'm not the one who wrote the mod code.  The bug was real and gladly fixed. Thanks. I made a suggestion to watch the use of a function known to catch devs unaware.

It obviously caught the dev unaware.  Don't take it so hard.
