### ISSUE TITLE
Is this an issue with MFR? re:   BlockFactoryGlassPane casting

### ISSUE THREAD

**Issue by sibomots** [powercrystals/MineFactoryReloaded#349]
What do you think?

MineFactoryReloaded-2.7.3-179.jar - latest (I believe)
(w/ Fancy Fences (9-8) v.4.0.0.zip ) - latest.

server: git-MCPC-Plus-jenkins-MCPC-Plus-156 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT)

Repro case:
0. Setup vanilla client with Forge 853
1. Login to world
2. Press E
3. Click "decoration tab"  in item browser.    

Result:
1. Delay half second
2. Closes window with crash log

Notes:
All the other tabs work in the item browser.
Same result in SSP or SMP

Full Log from client (in SMP)  http://pastebin.com/t52NWjL7

Server does not crash (or seem affected). No error in the server.  Only affects the client.

java.lang.ClassCastException: vanillawithsprinkles.fancyfences.modBlockPane cannot be cast to powercrystals.minefactoryreloaded.block.BlockFactoryGlassPane
    at powercrystals.minefactoryreloaded.render.item.FactoryGlassPaneItemRenderer.renderItem(FactoryGlassPaneItemRenderer.java:37)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:182)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlotItem(GuiContainer.java:485)
    at net.minecraft.client.gui.inventory.GuiContainer.func_74192_a(GuiContainer.java:472)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:150)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:683)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by sibomots** [comment]
Hang on, let me try the very latest artifacts on Jenkins..

MineFactoryReloaded-2.7.4B1-207.jar

I'll withdraw the issue if there's success.

Thanks

**Comment by sibomots** [comment]
OK well the problem is reproducible with the latest (#207) artifact.

But when I remove the VanillaWithSprinkles mod (FancyFences) then the problem is not present.

I'll have to dig further.

Thanks.

**Comment by skyboy** [comment]
FancyFences is overriding the glass pane (MFR does too), and the FancyFences item isn't what MFR expects - simply turn off (in the MFR config) VanillaOverride.GlassPane

**Comment by AEnterprise** [comment]
mayby forge could add something that gives an error (or at least a warning) when 2 different mods are overriding the same item

**Comment by DAOWAce** [comment]
So glad I found this.

Chisel was doing the same thing; would've probably never known unless I found this report.

Gonna just throw this in here to help anyone also googling like I was:

info.jbcs.minecraft.chisel.BlockMarblePane cannot be cast to powercrystals.minefactoryreloaded.block.BlockFactoryGlassPane
