### ISSUE TITLE
IllegalAccessError Crash

### ISSUE THREAD

**Issue by winstliu** [powercrystals/MineFactoryReloaded#36]
So, here's another crash for you to look at ;)  Forge 6.6.2.534, using Build 100 of MFR, PfF Build 30ish (from Jenkins), Nether Ores 2.0.6.28, Power Converters 2.2.2.26, Optifine Ultra D5.

`2013-02-26 20:35:09 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2013-02-26 20:35:09 [SEVERE] [ForgeModLoader] Caught exception from MFReloaded
java.lang.IllegalAccessError
    at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.load(MineFactoryReloadedCore.java:406)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:207)
    at net.minecraft.client.Minecraft.a(Minecraft.java:458)
    at asq.a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:746)
    at java.lang.Thread.run(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR] cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.transition(LoadController.java:130)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:677)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:207)
2013-02-26 20:35:19 [INFO] [STDERR]     at net.minecraft.client.Minecraft.a(Minecraft.java:458)
2013-02-26 20:35:19 [INFO] [STDERR]     at asq.a(SourceFile:56)
2013-02-26 20:35:19 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:746)
2013-02-26 20:35:19 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR] Caused by: java.lang.IllegalAccessError
2013-02-26 20:35:19 [INFO] [STDERR]     at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.load(MineFactoryReloadedCore.java:406)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-02-26 20:35:19 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
2013-02-26 20:35:19 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
2013-02-26 20:35:19 [INFO] [STDERR]     ... 5 more`

EDIT:  Not a PfF issue.

**Comment by powercrystals** [comment]
If you're using a beta MFR you gotta use a beta core too ;)

**Comment by winstliu** [comment]
<.< Stupid me :3
