### ISSUE TITLE
Crash on connect with client

### ISSUE THREAD

**Issue by olee** [powercrystals/MineFactoryReloaded#387]
Client crashes after connecting and rendering starts.

http://pastebin.com/Dbkm1BNx

```
java.lang.ArrayIndexOutOfBoundsException: 2
    at powercrystals.minefactoryreloaded.block.BlockRubberLeaves.func_149691_a(BlockRubberLeaves.java:65)
    at powercrystals.minefactoryreloaded.block.BlockRubberLeaves.func_149673_e(BlockRubberLeaves.java:58)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9361)
```

func_149691_a seems to be getIcon - but if I look into that function I can't see any reason for a ArrayIndexOutOfBoundsException...

https://github.com/powercrystals/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/block/BlockRubberLeaves.java

**Comment by olee** [comment]
Scrap that I got the wrong repository -.-'
