### ISSUE TITLE
LiquiCrafter crashes with empty RP2 fluid pipes

### ISSUE THREAD

**Issue by skyboy** [powercrystals/MineFactoryReloaded#39]
Correctable with:

```
    private int findFirstMatchingTank(LiquidStack liquid)
{
    if (liquid != null) for(int i = 0; i < 9; i++)
    {
        if(_tanks[i].getLiquid() != null && _tanks[i].getLiquid().itemID == liquid.itemID && _tanks[i].getLiquid().itemMeta == liquid.itemMeta)
        {
            return i;
        }
    }

    return -1;
}
```

and the stacktrace for reference:

```
java.lang.NullPointerException
at powercrystals.minefactoryreloaded.processing.TileEntityLiquiCrafter.findFirstMatchingTank(TileEntityLiquiCrafter.java:416)
at powercrystals.minefactoryreloaded.processing.TileEntityLiquiCrafter.getTank(TileEntityLiquiCrafter.java:379)
at com.eloraam.redpower.core.PipeLib.isConSide(PipeLib.java:33)
at com.eloraam.redpower.core.PipeLib.getConnections(PipeLib.java:49)
at com.eloraam.redpower.machine.RenderPipe.renderWorldBlock(RenderPipe.java:40)
at com.eloraam.redpower.core.CoreProxyClient$RenderHandler.renderWorldBlock(CoreProxyClient.java:62)
at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:142)
at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:87)
at bbb.b(RenderBlocks.java:572)
at baj.a(WorldRenderer.java:227)
at bav.a(RenderGlobal.java:1524)
at ban.a(EntityRenderer.java:1102)
at ban.b(EntityRenderer.java:974)
```

**Comment by powercrystals** [comment]
Nice catch!

**Comment by powercrystals** [comment]
Closing this, should be fixed now
