### ISSUE TITLE
Crash when changing video settings

### ISSUE THREAD

**Issue by BlaCoiso** [powercrystals/MineFactoryReloaded#433]
If I change some vídeo settings (for exemple anisostropic filtering) the game will crash.
Crash report:
Description: Registering texture

java.lang.NullPointerException: Registering texture
    at powercrystals.minefactoryreloaded.MineFactoryReloadedClient.setIcons(MineFactoryReloadedClient.java:283)
    at powercrystals.minefactoryreloaded.MineFactoryReloadedClient.onPostTextureStitch(MineFactoryReloadedClient.java:273)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_286_MineFactoryReloadedClient_onPostTextureStitch_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:276)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:303)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:965)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BlaCoiso** [comment]
Seems this is the wrong repo, going to try reporting it in https://github.com/skyboy/MineFactoryReloaded/issues/
