### ISSUE TITLE
safarinet and traincraft

### ISSUE THREAD

**Issue by quentfr21** [powercrystals/MineFactoryReloaded#66]
when i use safari net on train from traincraft it crash the server
i use the 1.4.7 version of mfr
---- Minecraft Crash Report ----
// Don't do that.

Time: 13/04/13 18:29
Description: Ticking entity

java.lang.ClassCastException: src.train.common.entity.rollingStock.EntityLocoSpeed cannot be cast to md
    at powercrystals.minefactoryreloaded.entity.EntitySafariNet.a(EntitySafariNet.java:66)
    at ri.j_(SourceFile:190)
    at yc.a(World.java:2293)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2255)
    at yc.h(World.java:2109)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at bdz.q(IntegratedServer.java:170)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by powercrystals** [comment]
This should already be fixed in the 1.5 version.
