### ISSUE TITLE
Biomes O' Plenty console spam

### ISSUE THREAD

**Issue by labpaw** [powercrystals/MineFactoryReloaded#98]
Just installed MFR and Biomes O' Plenty. So I got this:
2013-05-08 21:07:28 [FINEST] [MineFactoryReloaded|CompatBiomesOPlenty] Sending event FMLInitializationEvent to mod MineFactoryReloaded|CompatBiomesOPlenty
2013-05-08 21:07:28 [INFO] [STDERR] java.lang.ClassNotFoundException: tdwp_ftw.biomesop.configuration.BOPBlocks
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.Class.forName0(Native Method)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.Class.forName(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at powercrystals.minefactoryreloaded.modhelpers.biomesoplenty.BiomesOPlenty.load(BiomesOPlenty.java:74)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-05-08 21:07:28 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
2013-05-08 21:07:28 [INFO] [STDERR]     at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:206)
2013-05-08 21:07:28 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:447)
2013-05-08 21:07:28 [INFO] [STDERR]     at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
2013-05-08 21:07:28 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:732)
2013-05-08 21:07:28 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-05-08 21:07:28 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-05-08 21:07:28 [FINEST] [MineFactoryReloaded|CompatBiomesOPlenty] Sent event FMLInitializationEvent to mod MineFactoryReloaded|CompatBiomesOPlenty
Can't paste a ForgeModLoader-client-0.log it's bigger than 500 kbs.
Using around 80 mods. Forge 688, Biomes O' Plenty 0.5.2, MFR 2.5.4-665 also tried latest build 2.6.0B1-686
It's not gamebreaking, just a console spam.

**Comment by powercrystals** [comment]
Should be fixed in build 698

**Comment by labpaw** [comment]
Just tested it. Yes it's fixed. Good job!
